'use client';
import { Banknote, Check, Clock3, MapPin, MessageSquare, Navigation, Phone, Power, ShieldAlert, ShieldCheck, Smartphone, X } from 'lucide-react';
import { Avatar, Button, Chip, CountdownRing, Legs, Plate, Seal, Sheet, Stat, UnitBadge } from '@/components/ui';
import { formatClock, formatPEN, type Driver, type Membership, type Unit } from '@/data';
import type { DispatchJob } from '@/lib/dispatch';
import type { RoadRoute } from '@/lib/routing';
import c from './Conductor.module.css';

type Identity = { driver: Driver; unit: Unit; membership: Membership };
const paymentLabel = (payment: DispatchJob['paymentMethod']) => payment === 'yape' ? 'Yape' : 'efectivo';

export function SheetOffline({ identity, onGoOnline }: { identity: Identity; onGoOnline: () => void }) {
  const { driver, unit, membership } = identity;
  return <Sheet className={c.homeSheet}><div className={c.identityHero}><Seal size={72} className={c.identitySeal} /><div className={c.identityTop}><Avatar initials={driver.avatarSeed} size={50} ring /><div className={c.headText}><div className={c.eyebrow}>Conductor en turno</div><div className={c.identityName}>{driver.name.split(' ')[0]}, buen día</div><div className={c.identityVehicle}>{unit.marca} {unit.modelo} · {unit.anio}</div></div><UnitBadge n={unit.n} size="lg" /></div><div className={c.identityFoot}><Plate value={unit.placa} /><span>Juliaca · ubicación protegida</span></div></div><div className={c.verify}><ShieldCheck size={22} className={c.verifySeal} /><div className={c.verifyBody}><div className={c.verifyTitle}>Membresía activa</div><div className={c.verifyMeta}>Habilitado para recibir servicios · {membership.daysToExpire} días</div></div><Chip tone="success" dot>Al día</Chip></div><div className={c.actions}><Button size="xl" full onClick={onGoOnline}><Power size={21} />Empezar a recibir viajes</Button><div className={c.actionHint}>La central verá tu ubicación mientras estés disponible</div></div></Sheet>;
}

export function SheetMembershipBlocked({ identity }: { identity: Identity }) {
  return <Sheet className={c.homeSheet}><div className={`${c.verify} ${c.verifyBlocked}`}><ShieldAlert size={28} className={c.verifySeal} /><div className={c.verifyBody}><div className={c.verifyTitle}>Membresía vencida</div><div className={c.verifyMeta}>La Unidad {identity.unit.n} salió del pool de asignación</div></div></div><div className={c.blockedBody}><Seal size={86} /><h2>Regulariza tu habilitación</h2><p>Comunícate con la oficina gremial. Hasta entonces no podrás recibir propuestas.</p><Plate value={identity.unit.placa} /></div></Sheet>;
}

export function SheetOnline({ unit, onGoOffline }: { unit: Unit; onGoOffline: () => void }) {
  return <Sheet className={c.onlineSheet}><div className={c.availabilityCard}><span className={c.radar} aria-hidden><span /><span /><span /><span className={c.radarCore} /></span><div className={c.headText}><div className={c.eyebrow}>Unidad {unit.n} · ubicación activa</div><div className={c.availabilityTitle}>Disponible</div><div className={c.availabilityMeta}>Esperando una propuesta de la central</div></div><span className={c.liveSwitch}><span /></span></div><div className={`${c.metrics} ${c.metricsBoxed}`}><Stat label="Estado" value="En línea" sub="GPS compartido" size="sm" /><Stat label="Zona" value="Centro" sub="Juliaca" size="sm" /></div><div className={c.actions}><Button size="lg" variant="outline" full onClick={onGoOffline}><Power size={18} />Dejar de recibir viajes</Button></div></Sheet>;
}

export function SheetProposal({ job, secondsLeft, route, onAccept, onReject }: { job: DispatchJob; secondsLeft: number; route: RoadRoute | null; onAccept: () => void; onReject: () => void }) {
  return <Sheet grabber={false} className={c.proposalSheet}><div className={c.proposalHead}><div className={c.headText}><div className={c.eyebrow}>Propuesta exclusiva</div><div className={c.title}>Servicio para ti</div><div className={c.subtitle}>Acepta el precio completo, sin subasta</div></div><CountdownRing value={secondsLeft} total={22} size={58} urgent={secondsLeft <= 7} /></div><div className={c.fareHero}><div><span className={c.fareLabel}>Cobro por {paymentLabel(job.paymentMethod)}</span><span className={c.fareAmount}>{formatPEN(job.fare)}</span></div><div className={c.paymentMark}>{job.paymentMethod === 'yape' ? <Smartphone size={22} /> : <Banknote size={22} />}{paymentLabel(job.paymentMethod)}</div></div><div className={c.routeCard}><Legs from={job.pickupAddress} fromMeta={route ? `${(route.distanceMeters / 1000).toFixed(1)} km hasta el recojo` : 'Calculando ruta vial'} to={job.destinationAddress} /></div><div className={`${c.person} ${c.personCard}`}><Avatar initials={job.passengerName.slice(0, 2).toUpperCase()} size={40} /><div className={c.personBody}><div className={c.personName}>{job.passengerName}</div><div className={c.personMeta}>Cliente de la central · {job.passengerPhone}</div></div></div><div className={`${c.actions} ${c.actionsPair}`}><Button size="xl" variant="outline" onClick={onReject}><X size={19} />Rechazar</Button><Button size="xl" onClick={onAccept}><Check size={21} />Aceptar</Button></div></Sheet>;
}

function PassengerRow({ job }: { job: DispatchJob }) { return <div className={c.person}><Avatar initials={job.passengerName.slice(0, 2).toUpperCase()} size={44} /><div className={c.personBody}><div className={c.personName}>{job.passengerName}</div><div className={c.personMeta}>{job.passengerPhone}</div></div><div className={c.personActions}><a href={`tel:${job.passengerPhone}`} aria-label="Llamar al cliente"><Phone size={17} /></a><Button variant="ghost" size="sm"><MessageSquare size={17} /></Button></div></div>; }

export function SheetPickup({ job, route, remaining, onArrived }: { job: DispatchJob; route: RoadRoute | null; remaining: number; onArrived: () => void }) {
  const step = route?.steps.find((item) => item.distanceMeters > 20) ?? route?.steps[0];
  return <Sheet className={c.pickupSheet}><div className={c.navigationHero}><Navigation size={26} /><div><span>Siguiente indicación</span><strong>{step?.instruction ?? 'Ruta temporalmente no disponible'}</strong><small>{step?.street ?? 'Conserva el punto de recojo visible'}</small></div></div><div className={c.etaHero}><div className={c.etaNumber}>{Math.max(1, Math.ceil(remaining / 60))}<span>min</span></div><div className={c.etaBody}><span className={c.eyebrow}>Hasta el recojo</span><strong>{job.pickupAddress}</strong><span>{route ? `${(route.distanceMeters / 1000).toFixed(1)} km por calles` : 'Sin ruta vial'}</span></div></div><div className={c.personCard}><PassengerRow job={job} /></div><div className={c.actions}><Button size="xl" full onClick={onArrived}><MapPin size={19} />Ya llegué al punto</Button></div></Sheet>;
}

export function SheetArrived({ job, boardingLeft, onStart }: { job: DispatchJob; boardingLeft: number; onStart: () => void }) {
  return <Sheet className={c.arrivedSheet}><div className={c.head}><div className={c.headText}><div className={c.title}>Esperando a {job.passengerName.split(' ')[0]}</div><div className={c.subtitle}>{job.pickupAddress}</div></div></div><div className={c.boarding}><Clock3 size={24} className={c.boardingIcon} /><div className={c.boardingBody}><div className={c.boardingTitle}>Tiempo de embarque</div><div className={c.boardingMeta}>Máximo 2 min en vías saturadas</div></div><span className={c.boardingClock}>{formatClock(boardingLeft)}</span></div><div className={c.arrivedPassenger}><PassengerRow job={job} /></div><div className={c.actions}><Button size="xl" full onClick={onStart}><Check size={20} />Iniciar viaje</Button></div></Sheet>;
}

export function SheetTrip({ job, route, elapsed, remaining, onFinish }: { job: DispatchJob; route: RoadRoute | null; elapsed: number; remaining: number; onFinish: () => void }) {
  const step = route?.steps.find((item) => item.distanceMeters > 20) ?? route?.steps[0];
  return <Sheet className={c.tripSheet}><div className={c.navigationHero}><Navigation size={27} /><div><span>Ahora</span><strong>{step?.instruction ?? 'Ruta temporalmente no disponible'}</strong><small>{step?.street ?? job.destinationAddress}</small></div></div><div className={c.head}><div className={c.headText}><div className={c.subtitle}>Destino</div><div className={c.title}>{job.destinationAddress}</div></div><Chip tone="brand" large>{formatClock(elapsed)}</Chip></div><div className={`${c.metrics} ${c.metricsBoxed}`}><Stat label="Cobro" value={formatPEN(job.fare)} sub={paymentLabel(job.paymentMethod)} size="sm" /><Stat label="Restante" value={`${Math.max(1, Math.ceil(remaining / 60))} min`} sub={route ? `${(route.distanceMeters / 1000).toFixed(1)} km totales` : 'Sin ruta vial'} size="sm" /></div><div className={c.actions}><Button size="xl" variant="success" full onClick={onFinish}><Check size={21} />Llegué al destino</Button></div></Sheet>;
}

export function SheetFinished({ job, unit, onConfirm }: { job: DispatchJob; unit: Unit; onConfirm: () => void }) {
  return <Sheet className={c.finishedSheet}><div className={c.done}><span className={c.doneMark}><Check size={32} /></span><span className={c.doneLabel}>Confirma el cobro por {paymentLabel(job.paymentMethod)}</span><span className={c.doneAmount}>{formatPEN(job.fare)}</span></div><div className={c.finishedMeta}><UnitBadge n={unit.n} size="sm" />Servicio #{job.id} · {job.passengerName}</div><div className={c.actions}><Button size="xl" full onClick={onConfirm}>{job.paymentMethod === 'yape' ? <Smartphone size={19} /> : <Banknote size={19} />}Confirmar pago y finalizar</Button></div></Sheet>;
}
